export const Montserrat = {
  thin: 'Montserrat-Thin',
  ThinItalic: 'Montserrat-ThinItalic',
  Light: 'Montserrat-Light',
  LightItalic: 'Montserrat-LightItalic',
  Regular: 'Montserrat-Regular',
  Italic: 'Montserrat-Italic',
  SemiBold: 'Montserrat-SemiBold',
  MediumItalic: 'Montserrat-MediumItalic',
  BoldItalic: 'Montserrat-BoldItalic',
  BlackBold: 'Montserrat-Black',
  BlackItalicBold: 'Montserrat-BlackItalic',
};
export const Roboto = {
  Thin100: 'Roboto-Thin',
  Italic100: 'Robotot-ThinItalic',
  Light200: 'Roboto-Light',
  italic200: 'Roboto-LightItalic',
  Regular300: 'Roboto-Regular',
  Italic300: 'Roboto-Italic',
  SemiBold: 'Roboto-Medium',
  italic400: 'Roboto-MediumItalic',
  Italic500: 'Roboto-BoldItalic',
  BlackBold: 'Roboto-Black',
  Italic700: 'Roboto-BlackItalic',
};
